version: "3"

services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - 5432:5432
    tty: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - myNet

#  backend:
#    image: hlhl/jib-example
#    ports:
#      - 8080:8080
#    depends_on:
#      - database
#    container_name: backend
#    networks:
#      - myNet

networks:
  myNet: